In [2]:
import pandas as pd

## 1. Read the data set and replace dashes with 0 to make sure you can perform arithmetic operations on the data.

In [3]:
df = pd.read_csv("Laliga.csv")
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1

In [4]:
df2 = pd.read_csv("Laliga.csv", header=1,na_values = ["-"])

In [5]:
df2.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,33.0,23.0,8.0,8.0,3.0,4.0,79.0,1929,1929,1
1,2,Barcelona,86,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,25.0,25.0,12.0,12.0,4.0,6.0,83.0,1929,1929,1
2,3,Atletico Madrid,80,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,10.0,8.0,16.0,9.0,7.0,6.0,56.0,1929,2002-03,1
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,6.0,6.0,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,8.0,7.0,10.0,5.0,8.0,10.0,49.0,1929,1929,1

In [6]:
df2 = df2.fillna(0)
df2.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,33.0,23.0,8.0,8.0,3.0,4.0,79.0,1929,1929,1
1,2,Barcelona,86,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,25.0,25.0,12.0,12.0,4.0,6.0,83.0,1929,1929,1
2,3,Atletico Madrid,80,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,10.0,8.0,16.0,9.0,7.0,6.0,56.0,1929,2002-03,1
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,6.0,6.0,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,8.0,7.0,10.0,5.0,8.0,10.0,49.0,1929,1929,1

## 2. Print all the teams which have started playing between 1930-1980.

In [7]:
pd.to_datetime(df2.Debut,errors='ignore')
df2.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,33.0,23.0,8.0,8.0,3.0,4.0,79.0,1929,1929,1
1,2,Barcelona,86,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,25.0,25.0,12.0,12.0,4.0,6.0,83.0,1929,1929,1
2,3,Atletico Madrid,80,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,10.0,8.0,16.0,9.0,7.0,6.0,56.0,1929,2002-03,1
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,6.0,6.0,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,8.0,7.0,10.0,5.0,8.0,10.0,49.0,1929,1929,1

In [8]:
df3 = df2.loc[(df2['Debut'] >= '1930') & (df2['Debut'] <= '1980')]

In [9]:
df3.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,6.0,6.0,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1
5,6,Sevilla,73,2819.0,2408.0,990.0,531.0,887.0,3680.0,3373.0,1.0,4.0,4.0,5.0,12.0,6.0,32.0,1934-35,2001-02,1
8,9,Zaragoza,58,2109.0,1986.0,698.0,522.0,766.0,2683.0,2847.0,0.0,1.0,4.0,5.0,4.0,4.0,18.0,1939-40,2012-13,2
9,10,Real Betis,51,1884.0,1728.0,606.0,440.0,682.0,2159.0,2492.0,1.0,0.0,2.0,3.0,4.0,4.0,14.0,1932-33,2015-16,1
10,11,Deportivo La Coruna,45,1814.0,1530.0,563.0,392.0,575.0,2052.0,2188.0,1.0,5.0,4.0,1.0,0.0,1.0,12.0,1941-42,2014-15,1

## 3.Print the list of teams which came Top 5 in terms of points

In [15]:
df2.sort_values(by="Points", ascending=True)
df2.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,33.0,23.0,8.0,8.0,3.0,4.0,79.0,1929,1929,1
1,2,Barcelona,86,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,25.0,25.0,12.0,12.0,4.0,6.0,83.0,1929,1929,1
2,3,Atletico Madrid,80,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,10.0,8.0,16.0,9.0,7.0,6.0,56.0,1929,2002-03,1
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,6.0,6.0,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,8.0,7.0,10.0,5.0,8.0,10.0,49.0,1929,1929,1

## 4. Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. Using the same function, find the team which has maximum and minimum goal difference

In [11]:
def goal_diff_count(gf,ga):
    return gf - ga

In [12]:
goal_diff_count(df2.GoalsFor,df2.GoalsAgainst).max()

2807.0

In [13]:
goal_diff_count(df2.GoalsFor,df2.GoalsAgainst).min()

-525.0

## 5.Create a new column with name “Winning Percent” and append it to the data set (5 points)
### Percentage of Winning = (GamesWon / GamesPlayed)*100
### If there are any numerical error, replace it with 0%
### Print the top 5 teams which has the highest Winning percentage

In [17]:
df2["Winning Percentage"] = df2.GamesWon / df2.GamesPlayed * 100

In [20]:
df2.sort_values(by="Winning Percentage",ascending=False).head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,...,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition,Winning Percentage
0,1,Real Madrid,86,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,...,23.0,8.0,8.0,3.0,4.0,79.0,1929,1929,1,59.630702
1,2,Barcelona,86,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,...,25.0,12.0,12.0,4.0,6.0,83.0,1929,1929,1,57.241130
2,3,Atletico Madrid,80,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,...,8.0,16.0,9.0,7.0,6.0,56.0,1929,2002-03,1,47.475134
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,...,6.0,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1,44.557057
4,5,Athletic Bilbao,86,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,...,7.0,10.0,5.0,8.0,10.0,49.0,1929,1929,1,43.772629

## 6.Group teams based on their “Best position” and print the sum of their points for all positions

In [189]:
df2.groupby("BestPosition")["Points"].sum()

BestPosition
1     27933.0
2      6904.0
3      5221.0
4      6563.0
5      1884.0
6      2113.0
7      1186.0
8      1134.0
9        96.0
10      450.0
11      445.0
12      511.0
14       71.0
15       14.0
16       81.0
17      266.0
19       81.0
20       34.0
Name: Points, dtype: float64